"""
Document model.

Task 3B Checkpoint 1 scope: schema only. No storage service, no
upload endpoint, no parsing — those arrive in later checkpoints. This
file should only ever describe the shape of the `documents` table.
"""
import uuid

from sqlalchemy import BigInteger, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import BaseModel


class Document(BaseModel):
    __tablename__ = "documents"

    # Plain FK column, deliberately with no relationship() on either
    # side (no User.documents, no Document.user) for this checkpoint.
    #
    # Reason: this project uses async SQLAlchemy throughout, where a
    # default (lazy="select") relationship raises MissingGreenlet at
    # runtime if accessed outside an explicit await — a real footgun
    # for whoever first writes `current_user.documents` in a route
    # handler with no reason to expect it. The correct loading
    # strategy (lazy="selectin", or AsyncAttrs.awaitable_attrs) is a
    # decision best made at the same time as the first real call site
    # that needs it (expected in a later checkpoint), not speculatively
    # here with nothing to consume it. Explicit `select(Document).where
    # (Document.user_id == ...)` queries are the correct pattern for
    # "list this user's documents" regardless, so nothing is lost by
    # deferring — this can be added additively later without a
    # migration change.
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )

    # Display-only — never used to construct a filesystem path.
    # 255 matches the filename-length ceiling most real filesystems
    # (ext4, NTFS, APFS) enforce on a single path component.
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)

    # The on-disk filename, generated by the storage service (later
    # checkpoint) as a UUID4 + whitelisted extension (.pdf/.docx/.txt)
    # — always exactly 41 characters. 64 is rounded up from that exact
    # bound: tight enough to document the format contract and fail
    # loudly if the storage service ever produces something
    # unexpected, loose enough to have real headroom.
    stored_filename: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)

    content_type: Mapped[str] = mapped_column(String(100), nullable=False)

    # BIGINT rather than INTEGER: trivial cost, avoids a future
    # migration if the upload cap ever grows past INTEGER's range.
    file_size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)

    # Deliberately loose (500): the actual on-disk directory layout
    # (flat vs. per-user subdirectories vs. date-based) is a
    # Checkpoint 2 decision, not yet made. Loose here so that decision
    # doesn't force a schema migration once it's made.
    storage_path: Mapped[str] = mapped_column(String(500), nullable=False)

    def __repr__(self) -> str:
        return f"<Document id={self.id} original_filename={self.original_filename!r}>"
