"""add embedding column to document_chunks

Revision ID: 368647c4431f
Revises: 411324fb18f5
Create Date: 2026-08-12 13:28:25.534097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '368647c4431f'
down_revision: Union[str, None] = '411324fb18f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable the pgvector extension before using its Vector type —
    # required once, per database. The project's docker-compose.yml
    # already uses the pgvector/pgvector:pg16 image (the extension
    # binary is present), but the extension still needs to be
    # explicitly enabled inside each database via this statement; a
    # fresh database (any environment, including a fresh production
    # deploy) would otherwise fail the same way this one did before
    # this line was added.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding')
    # Deliberately not dropping the vector extension here — other
    # tables/migrations may come to depend on it, and dropping/
    # re-creating extensions on every up/down cycle is not standard
    # practice; leaving it enabled once turned on is the safer default.
    # ### end Alembic commands ###
