"""create document_chunks table

Revision ID: 411324fb18f5
Revises: f5a18872f21b
Create Date: 2026-08-11 21:34:08.950730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '411324fb18f5'
down_revision: Union[str, None] = 'f5a18872f21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('document_text_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_text_id'], ['document_texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_text_id', 'chunk_index', name='uq_document_chunks_text_index')
    )
    op.create_index(op.f('ix_document_chunks_document_text_id'), 'document_chunks', ['document_text_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_document_text_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
